python main.py \
    --dataset_file coco \
    --coco_path ./datasets/path/to/coco \
    --output_dir ./datasets/path/to/output \
    --epochs 10 \
    --lr 1e-3 \
    --weight_decay 1e-3 \
    --batch_size 2 \
    | tee training.log